var tableFactory=function(B,C){function u(){var a=g.length,b=m.pagination,c,e=Math.ceil(a/b.length),h=0;if(a>b.length){c=p.querySelector(".lt-footer")||document.createDocumentFragment().appendChild(document.createElement("DIV"));c.className="lt-footer";for(c.innerHTML="Total: "+a+" | Pages: ";h<e;h++)c.innerHTML+='<a href="#'+h+'" >'+h+"</a> | ";c.onclick=function(a){a=a.target;"A"===a.tagName&&(b.start=parseInt(a.innerHTML),w(),s())};p.appendChild(c)}}function t(a,b){return RegExp("(?:^|\\s)"+b+
"(?!\\S)").test(a.className)}function x(a){for(var b=0;null!==(a=a.previousSibling);)++b;return b}function D(a){if("SPAN"===a.target.tagName&&t(a.target,"sort")){a=a.target;var b=a.parentNode.parentNode,c=t(a,"desc-sort")?"-desc":"-asc",e;if(m.pagination)e=parseInt(b.getAttribute("data-column-number")),g.sort(function(a,b){return F[m.columns[e].type+c](a,b,m.columns[e].prop)}),w(),s();else{var h=p.querySelectorAll("tbody tr"),h=Array.prototype.slice.call(h,0),d=0,k=x(b),f=parseInt(b.getAttribute("data-column-number")),
b=h.length;for(h.sort(function(a,b){return G[m.columns[f].type+c](a,b,k+1)});d<b;)h[d].className=0===d%2?"oddrow":"evenrow",p.querySelector("tbody").appendChild(h[d++])}a.className="-desc"===c?a.className.replace("desc-sort","asc-sort"):a.className.replace("asc-sort","desc-sort")}}function y(a){Array.isArray(a)||(a=[a]);var b=0,c=a.length,v=e.getElementsByTagName("TBODY")[0],h=m.columns,d=v.querySelectorAll("tr").length,k,f,j,E=h.length;f=0;for(var q,l,g;b<c;b++){k=a[b];f=d+b;r[r.length]=k;j=v.insertRow(-1);
j.className+=0===f%2?"oddrow":"evenrow";j.setAttribute("data-index",f);for(f=0;f<E;)q=h[f++],!1!==q.visible&&(l=j.insertCell(-1),g=l.appendChild(document.createElement("DIV")),l.title=k[q.prop],g.innerHTML=k[q.prop])}}function z(){for(var a=[e.getElementsByTagName("COLGROUP")[0],e.getElementsByTagName("THEAD")[0].firstChild,e.getElementsByTagName("TBODY")[0],e.getElementsByTagName("TFOOT")[0]],b=a.length,c;b--;)if(c=a[b])for(;c.lastChild;)c.removeChild(c.lastChild)}function w(){for(var a=e.getElementsByTagName("TBODY")[0];a.lastChild;)a.removeChild(a.lastChild)}
function A(a,b,c){var e=b.appendChild(document.createElement("DIV"));e.innerHTML=a.name;b.setAttribute("data-column-number",c);m.sortable&&a.sort&&(b.setAttribute("data-column",a.name),b.setAttribute("data-sorting",a.sort),a=e.appendChild(document.createElement("span")),a.className="sort desc-sort",a.innerHTML="&nbsp")}function s(a){g=a||g;a=e.querySelector("tbody");a.onmouseover=function(a){a=a.target;a=("TD"===a.tagName?a:a.parentNode).parentNode;a.setAttribute("row-color",a.style.backgroundColor);
a.style.backgroundColor="#ffff66"};a.onmouseout=function(a){a=a.target;a=("TD"===a.tagName?a:a.parentNode).parentNode;a.style.backgroundColor=a.getAttribute("row-color")};a=m.pagination;var b;a&&a.length<g.length?(b=(a.start||0)*a.length,a=g.slice(b,b+a.length)):a=g;y(a)}var n={number:function(a,b,c){return c?parseFloat(a)>=parseFloat(b):parseFloat(b)>=parseFloat(a)},string:function(a,b,c){return c?a>=b:b>=a}},G={"number-desc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+
c+")");return n.number(a.innerText||a.textContent,b.innerText||b.textContent)},"number-asc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+c+")");return n.number(a.innerText||a.textContent,b.innerText||b.textContent,!0)},"string-desc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+c+")");return n.string(a.innerText||a.textContent,b.innerText||b.textContent)},"string-asc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+
c+")");b=b.querySelector("tr td:nth-of-type("+c+")");return n.string(a.innerText||a.textContent,b.innerText||b.textContent,!0)}},F=Object.create(null,{"number-desc":{get:function(a,b,c){return n.number(a[c],b[c])},writable:!1},"number-asc":{get:function(a,b,c){return n.number(a[c],b[c],!0)},enumerable:!0},"string-desc":{get:function(a,b,c){return n.string(a[c],b[c])},enumerable:!0},"string-asc":{get:function(a,b,c){return n.string(a[c],b[c],!0)},enumerable:!0}}),H={draw:function(a){z();for(var b=
e.getElementsByTagName("THEAD")[0].firstChild,c=m.columns,g=c.length,h=0,d,k;h<g;h++)d=c[h],!1!==d.visible&&(k=b.appendChild(document.createElement("TH")),A(d,k,h));s(a);if(m.sortable&&(a=e.querySelector("thead")))a.onclick=D;m.editable&&(e.querySelector("tbody").onclick=function(a){if(t(e,"edit-state"))e.className=e.className.replace("edit-state","");else{e.className+=" edit-state";var b="TD"===a.target.tagName?a.target:a.target.parentNode,c=b.querySelector("div"),d=document.createElement("input");
d.type="text";d.style.width=b.style.width;d.value=b.innerText||b.textContent;c.style.display="none";b.appendChild(d);d.onblur=function(){c.innerText=c.textContent=d.value;b.removeChild(d);c.style.display="block"};d.focus()}});m.pagination&&u()},clear:z,addRows:function(a){g.push(a);var b=m.pagination;b&&b.length<g.length?u():y(a)},removeRows:function(a){for(var b=[],c=0,g=0;c<a.length;c++)b.push(e.querySelectorAll("tbody tr")[a[c]]);for(;g<b.length;g++)e.querySelector("tbody").removeChild(b[g])},
setColumns:function(a){Array.isArray(a)||(a=[a]);for(var b=a.length,c=0,g=e.getElementsByTagName("THEAD")[0].firstChild,h=m.columns,d,k,f,j;c<b;)if(d=a[c++],j=d.index,k=h[j],k.visible=d.visible){a:{d=j;f=e.querySelectorAll("th");for(var n=0,q=f.length,l=void 0,p=void 0;n<q;n++)if(l=f[n],p=l.getAttribute("data-column-number"),p>d){f=l;break a}f=null}d=document.createElement("TH");f?g.insertBefore(d,f):g.appendChild(d);f=x(d);A(k,d,j);j=f;d=1;f=e.rows;n=f.length;for(p=l=q=q=l=void 0;d<n;d++)l=f[d],
q=l.getAttribute("data-index"),q=r[q][k.prop],l=l.insertCell(j),p=l.appendChild(document.createElement("DIV")),l.title=q,p.innerHTML=q}else{d=e.querySelector('[data-column-number="'+j+'"]');k=e.querySelectorAll("tr td:nth-of-type("+(j+1)+")");f=k.length;j=0;for(d.parentNode.removeChild(d);j<f;)k[j].parentNode.removeChild(k[j++])}},getData:function(){return r}},p=B,m=C,e,r=[],g=[];e=p.getElementsByTagName("TABLE")[0];e||(e='<table class="ui-table"><colgroup></colgroup><caption></caption><thead><tr></tr></thead><tbody></tbody></table>',
p.innerHTML=e,e=p.getElementsByTagName("TABLE")[0]);return H};window.lightTable=tableFactory;
