var tableFactory=function(y,z){function t(a){return RegExp("(?:^|\\s)"+a+"(?!\\S)").test(this.className)}function u(a){for(var b=0;null!==(a=a.previousSibling);)++b;return b}function A(a){if("SPAN"===a.target.tagName&&t.call(a.target,"sort")){a=a.target;var b=a.parentNode.parentNode,e=t.call(a,"desc-sort")?"-desc":"-asc",c=r.querySelectorAll("tbody tr"),c=Array.prototype.slice.call(c,0),l=u(b),d=parseInt(b.getAttribute("data-column-number")),b=c.length,g=0;for(c.sort(function(a,b){return B[n.columns[d].type+
e](a,b,l+1)});g<b;)c[g].className=0===g%2?"oddrow":"evenrow",r.querySelector("tbody").appendChild(c[g++]);a.className="-desc"===e?a.className.replace("desc-sort","asc-sort"):a.className.replace("asc-sort","desc-sort")}}function v(a){Array.isArray(a)||(a=[a]);for(var b=0,e=a.length,k=c.getElementsByTagName("TBODY")[0],l=n.columns,d=k.querySelectorAll("tr").length,g,f,h,p=l.length,m=0,j,q;b<e;b++){g=a[b];f=d+b;s[s.length]=g;h=k.insertRow(-1);h.className+=0===f%2?"oddrow":"evenrow";for(h.setAttribute("data-index",
f);m<p;)f=l[m++],!1!==f.visible&&(j=h.insertCell(-1),q=j.appendChild(document.createElement("DIV")),j.title=g[f.prop],q.innerHTML=g[f.prop])}}function w(){for(var a=[c.getElementsByTagName("COLGROUP")[0],c.getElementsByTagName("THEAD")[0].firstChild,c.getElementsByTagName("TBODY")[0],c.getElementsByTagName("TFOOT")[0]],b=a.length,e;b--;)if(e=a[b])for(;e.lastChild;)e.removeChild(e.lastChild)}function x(a,b,e){var c=b.appendChild(document.createElement("DIV"));c.innerHTML=a.name;b.setAttribute("data-column-number",
e);n.sortable&&a.sort&&(b.setAttribute("data-column",a.name),b.setAttribute("data-sorting",a.sort),a=c.appendChild(document.createElement("span")),a.className="sort desc-sort",a.innerHTML="&nbsp")}var B={"number-desc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+c+")");c=a.innerText||a.textContent;return parseFloat(b.innerText||b.textContent)>=parseFloat(c)},"number-asc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+
c+")");b=b.innerText||b.textContent;return parseFloat(a.innerText||a.textContent)>=parseFloat(b)},"string-desc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+c+")");return(b.innerText||b.textContent)>=(a.innerText||a.textContent)},"string-asc":function(a,b,c){a=a.querySelector("tr td:nth-of-type("+c+")");b=b.querySelector("tr td:nth-of-type("+c+")");return(a.innerText||a.textContent)>=(b.innerText||b.textContent)}},C={draw:function(a){w();for(var b=
c.getElementsByTagName("THEAD")[0].firstChild,e=n.columns,k=e.length,l=0,d,g;l<k;l++)d=e[l],!1!==d.visible&&(g=b.appendChild(document.createElement("TH")),x(d,g,l));b=c.querySelector("tbody");b.onmouseover=function(a){a=("TD"===a.target.tagName?a.target:a.target.parentNode).parentNode;a.setAttribute("row-color",a.style.backgroundColor);a.style.backgroundColor="#ffff66"};b.onmouseout=function(a){a=("TD"===a.target.tagName?a.target:a.target.parentNode).parentNode;a.style.backgroundColor=a.getAttribute("row-color")};
v(a);if(n.sortable&&(a=c.querySelector("thead")))a.onclick=A;n.editable&&(c.querySelector("tbody").onclick=function(a){if(t.call(c,"edit-state"))c.className=c.className.replace("edit-state","");else{c.className+=" edit-state";var b="TD"===a.target.tagName?a.target:a.target.parentNode,e=b.querySelector("div"),d=document.createElement("input");d.type="text";d.style.width=b.style.width;d.value=b.innerText||b.textContent;e.style.display="none";b.appendChild(d);d.onblur=function(){e.innerText=e.textContent=
d.value;b.removeChild(d);e.style.display="block"};d.focus()}})},clear:w,addRows:v,removeRows:function(a){for(var b=[],e=0,k=0;e<a.length;e++)b.push(c.querySelectorAll("tbody tr")[a[e]]);for(;k<b.length;k++)c.querySelector("tbody").removeChild(b[k])},setColumns:function(a){Array.isArray(a)||(a=[a]);for(var b=a.length,e=0,k=c.getElementsByTagName("THEAD")[0].firstChild,l=n.columns,d,g,f,h;e<b;)if(d=a[e++],g=l[d.index],g.visible=d.visible){a:{f=d.index;h=c.querySelectorAll("th");for(var p=0,m=h.length,
j=void 0,q=void 0;p<m;p++)if(j=h[p],q=j.getAttribute("data-column-number"),q>f){f=j;break a}f=null}f=f?k.insertBefore(document.createElement("TH"),f):k.appendChild(document.createElement("TH"));h=u(f);x(g,f,d.index);d=h;f=1;h=c.rows;for(p=h.length;f<p;f++)j=h[f],m=j.getAttribute("data-index"),m=s[m][g.prop],j=j.insertCell(d),q=j.appendChild(document.createElement("DIV")),j.title=m,q.innerHTML=m}else{g=c.querySelector('[data-column-number="'+d.index+'"]');d=c.querySelectorAll("tr td:nth-of-type("+
(d.index+1)+")");f=d.length;h=0;for(g.parentNode.removeChild(g);h<f;)d[h].parentNode.removeChild(d[h++])}},getData:function(){return s}},r=y,n=z,c,s=[];c=r.getElementsByTagName("TABLE")[0];c||(c='<table class="ui-table"><colgroup></colgroup><caption></caption><thead><tr></tr></thead><tbody></tbody></table>',r.innerHTML=c,c=r.getElementsByTagName("TABLE")[0]);return C};window.lightTable=tableFactory;
